<?php
$defaults=array(
   'title' => __('Categories', 'collapsing-categories'),
   'showPostCount' => true,
   'inExclude' => 'exclude',
   'inExcludeCats' => '1',
   'showPosts' => true, 
   'showPages' => false,
   'linkToCat' => true,
   'olderThan' => 0,
   'excludeAll' => '1',
   'catSortOrder' => 'ASC',
   'catSort' => 'catName',
   'postSortOrder' => 'ASC',
   'postSort' => 'postTitle',
   'expand' => '0',
   'defaultExpand' => '',
   'debug'=>'0',
   'postTitleLength' => 0,
   'catfeed' => 'none',
   'taxonomy' => 'category',
   'post_type' => 'post',
   'postDateAppend' => 'after',
   'postDateFormat' => 'm/d',
   'showPostDate' => false,
   'useCookies' => true,
   'postsBeforeCats' => false,
   'expandCatPost' => false,
   'showEmptyCat' => false,
   'showTopLevel' => false
);
?>
